const API="";
let mode="login";
let user=JSON.parse(localStorage.getItem("fdm_user")||"null");
let token=localStorage.getItem("fdm_token")||"";
let cache={me:null,history:[],tx:[],adminStats:null,adminSub:[],adminWd:[],members:[],stock:[],settings:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const rupiah=n=>"Rp "+Number(n||0).toLocaleString("id-ID");
const date=v=>v?new Date(String(v).replace(" ","T")+"Z").toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"-";
async function api(path,opts={}){const headers={"Content-Type":"application/json",...(opts.headers||{})};if(token)headers.Authorization="Bearer "+token;const r=await fetch(API+path,{...opts,headers});let data={};try{data=await r.json()}catch{}if(!r.ok){if(r.status===401){logout(false);throw new Error("Sesi login berakhir.")}throw new Error(data.error||"Permintaan gagal")}return data}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2800)}
function setMsg(msg){$("authMsg").textContent=msg;$("authMsg").classList.toggle("hidden",!msg)}
function togglePassword(){const x=$("password");x.type=x.type==="password"?"text":"password"}
function toggleConfirmPassword(){const x=$("confirmPassword");x.type=x.type==="password"?"text":"password"}
function toggleAuth(){mode=mode==="login"?"register":"login";const reg=mode==="register";$("authTitle").textContent=reg?"Buat Akun":"Masuk";$("authSubtitle").textContent=reg?"Daftar untuk mendapatkan akses penuh ke semua fitur FinzyDevMail.":"Masuk untuk melanjutkan ke dashboard FinzyDevMail dan kelola semua fitur.";$("authButton").innerHTML=reg?"♙ &nbsp; Daftar":"↪ &nbsp; Masuk";$("switchAuth").innerHTML=reg?"Sudah punya akun? <b>Masuk →</b>":"Belum punya akun? <b>Daftar →</b>";$("nameWrap").classList.toggle("hidden",!reg);$("confirmWrap").classList.toggle("hidden",!reg);$("termsWrap").classList.toggle("hidden",!reg);$("authMeta").classList.toggle("hidden",reg);$("telegramBtn").classList.toggle("hidden",!reg);setMsg("")}
async function submitAuth(){setMsg("");const email=$("email").value.trim(),password=$("password").value,name=$("name").value.trim();if(!email||!password||(mode==="register"&&!name)){setMsg("Lengkapi semua data terlebih dahulu.");return}if(mode==="register"){const confirm=$("confirmPassword").value;if(password!==confirm){setMsg("Konfirmasi password tidak sama.");return}if(!$("terms").checked){setMsg("Setujui Syarat & Ketentuan terlebih dahulu.");return}}try{const data=await api(mode==="login"?"/api/auth/login":"/api/auth/register",{method:"POST",body:JSON.stringify({email,password,name})});token=data.token;user=data.user;localStorage.setItem("fdm_token",token);localStorage.setItem("fdm_user",JSON.stringify(user));boot()}catch(e){setMsg(e.message)}}
function googleLogin(){toast("Google OAuth perlu Client ID dan redirect URI di server.")}
function logout(show=true){token="";user=null;cache={me:null,history:[],tx:[],adminStats:null,adminSub:[],adminWd:[],members:[],stock:[],settings:null};localStorage.removeItem("fdm_token");localStorage.removeItem("fdm_user");boot();if(show)toast("Kamu sudah keluar")}
async function boot(){document.body.classList.toggle("auth-active",!token);if(!token){$("auth").classList.remove("hidden");$("app").classList.add("hidden");$("userNav").classList.add("hidden");$("adminNav").classList.add("hidden");return}try{cache.me=await api("/api/me");user=cache.me.user;localStorage.setItem("fdm_user",JSON.stringify(user));$("auth").classList.add("hidden");$("app").classList.remove("hidden");document.body.classList.remove("auth-active");setupRole();show(user.role==="admin"?"admin":"home")}catch{logout(false)}}
function setupRole(){const admin=user?.role==="admin";$("userNav").classList.toggle("hidden",admin);$("adminNav").classList.toggle("hidden",!admin);$("roleBadge").textContent=admin?"ADMIN":"USER"}
function activeNav(p){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p))}
function show(p){activeNav(p);const views={home:viewHome,job:viewJob,generate:viewGenerate,checker:viewChecker,history:viewHistory,profile:viewProfile,balance:viewBalance,admin:viewAdmin,adminSub:viewAdminSub,adminWd:viewAdminWd,members:viewMembers,stock:viewStock,adminSettings:viewAdminSettings};if(views[p])views[p]()}
function shell(title,sub,icon="✦",kicker="FINZYDEVMAIL"){$("page").innerHTML=`<div class="hero glass"><div class="hero-copy"><div class="eyebrow small">${esc(kicker)}</div><div class="muted hero-sub">${esc(sub||"")}</div><h1>${esc(title)}</h1></div><div class="hero-orb">${icon}</div></div>`}
function renderHistory(items){if(!items?.length)return `<div class="empty">Belum ada aktivitas.</div>`;const price=Number(cache.settings?.price_per_email||3800);return items.map(x=>`<button class="item item-button" onclick="showSubmission(${x.id})"><div class="item-main"><b>Setoran #${x.id}</b><small>${date(x.created_at)} • ${x.total_items} email</small></div><div class="item-side"><span class="status ${x.status==="DITERIMA"?"ok":x.status==="DITOLAK"?"bad":x.status==="SEBAGIAN"?"partial":"pending"}">${esc(x.status)}</span><small>${x.status==="DITERIMA"?rupiah(Number(x.accepted_items||0)*price):"Lihat detail →"}</small></div></button>`).join("")}
async function viewHome(){try{cache.me=await api("/api/me");cache.history=(await api("/api/history")).items||[];cache.tx=(await api("/api/transactions")).items||[];cache.settings=await api("/api/settings");user=cache.me.user}catch(e){toast(e.message);return}const u=user||{},total=cache.history.reduce((a,x)=>a+Number(x.total_items||0),0),accepted=cache.history.reduce((a,x)=>a+Number(x.accepted_items||0),0),price=Number(cache.settings.price_per_email||3800);shell("Halo, "+(u.name||u.email.split("@")[0]),"Dashboard FinzyDevMail • akun kamu siap digunakan","✦","DASHBOARD");$("page").innerHTML+=`<div class="card balance-card glass"><div class="label">Saldo tersedia</div><div class="money">${rupiah(u.balance)}</div><div class="balance-foot"><span class="reward">Reward setor ${rupiah(price)} / email</span><button class="mini-action" onclick="show('balance')">Tarik saldo →</button></div></div><div class="grid grid-3"><div class="stat glass"><span class="label">Total email</span><span class="big">${total}</span></div><div class="stat glass"><span class="label">Diterima</span><span class="big green">${accepted}</span></div><div class="stat glass"><span class="label">Setoran</span><span class="big cyan">${cache.history.length}</span></div></div><div class="section-title"><h2>Aktivitas terbaru</h2><span>Live dari server</span></div><div class="card glass">${renderHistory(cache.history.slice(0,6))}</div><div class="section-title"><h2>Akses cepat</h2></div><div class="grid"><button class="quick-card glass" onclick="show('job')"><span>▣</span><b>Setor Gmail</b><small>Kirim daftar email</small></button><button class="quick-card glass" onclick="show('checker')"><span>✓</span><b>Checker Gmail</b><small>Cek alamat @gmail.com</small></button><button class="quick-card glass" onclick="show('generate')"><span>✦</span><b>Generate</b><small>Ambil stok tersedia</small></button></div>`}
async function viewJob(){try{cache.settings=await api("/api/settings")}catch(e){toast(e.message);return}const price=Number(cache.settings.price_per_email||3800);shell("Setor Gmail","Kirim daftar email yang memang kamu miliki/berhak kamu serahkan.","▣","SETORAN");$("page").innerHTML+=`<div class="card glass"><div class="row"><div><b>Reward per email</b><div class="muted">${rupiah(price)} setelah disetujui admin</div></div><span class="reward">SETORAN</span></div><div class="section-title"><h2>Aturan setoran</h2><span>Admin</span></div><div class="notice rules-box">${esc(cache.settings.submission_rules||"").replace(/\n/g,"<br>")}</div><div class="section-title"><h2>Daftar email</h2><span>1 email / baris</span></div><textarea id="emails" placeholder="contoh@gmail.com
contoh2@gmail.com"></textarea><div class="btn-row"><button class="btn primary" onclick="submitJob()">Kirim Setoran</button><button class="btn" onclick="$('emails').value=''">Bersihkan</button><button class="btn" onclick="show('checker')">✓ Checker Gmail</button></div></div>`}
async function submitJob(){const emails=$("emails").value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!emails.length){toast("Masukkan minimal satu email.");return}try{const r=await api("/api/submissions",{method:"POST",body:JSON.stringify({emails})});toast(`Setoran #${r.submission_id} dibuat • ${r.total_items} email`);$("emails").value="";showSubmission(r.submission_id)}catch(e){toast(e.message)}}
async function viewGenerate(){let stock={available:0};try{stock=await api("/api/stock")}catch(e){toast(e.message);return}shell("Generate","Generate sekarang mengambil alamat dari stok yang dimasukkan admin.","✦","STOK & GENERATE");$("page").innerHTML+=`<div class="card glass stock-generator"><div class="stock-head"><div><span class="label">Stok tersedia</span><strong>${stock.available}</strong><small>Email siap diambil</small></div><span class="stock-glow">✦</span></div><div class="grid"><div><label class="label">Jumlah</label><input id="stockCount" type="number" min="1" max="100" value="10"></div><div class="stock-note"><span>✓</span><div><b>Admin-managed stock</b><small>Tidak membuat akun Gmail baru.</small></div></div></div><div class="btn-row"><button class="btn primary" onclick="claimStock()">✦ Ambil dari Stok</button><button class="btn" onclick="copyOut()">Salin hasil</button></div><textarea id="out" readonly placeholder="Email dari stok akan muncul di sini"></textarea></div>`}
async function claimStock(){const count=Math.min(100,Math.max(1,Number($("stockCount").value)||1));try{const r=await api("/api/stock/claim",{method:"POST",body:JSON.stringify({count})});$("out").value=r.items.join("\n");toast(`${r.count} email diambil dari stok`)}catch(e){toast(e.message)}}
async function copyOut(){const v=$("out")?.value||"";if(!v){toast("Belum ada hasil untuk disalin.");return}try{await navigator.clipboard.writeText(v);toast("Hasil disalin")}catch{toast("Clipboard tidak tersedia")}}
async function viewChecker(){
  shell("Checker Gmail","Periksa daftar alamat @gmail.com menggunakan NetNIT Deep Check. API key tetap disimpan di server.","✓","CHECKER GMAIL");
  $("page").innerHTML+=`<div class="card glass">
    <div class="notice compact"><b>Checker Gmail</b><br>Masukkan alamat Gmail yang ingin diperiksa, satu alamat per baris. Hasil LIVE/INVALID mengikuti status yang dikembalikan NetNIT. UNKNOWN berarti NetNIT tidak memberikan status good/bad yang cukup.</div>
    <div class="section-title"><h2>Daftar Gmail</h2><span>maks. 500</span></div>
    <textarea id="checkerEmails" placeholder="contoh@gmail.com
nama.lain@gmail.com"></textarea>
    <div class="btn-row">
      <button class="btn primary" onclick="runGmailChecker()">✓ Cek Gmail</button>
      <button class="btn" onclick="$('checkerEmails').value='';$('checkerResults').innerHTML=''">Bersihkan</button>
      <button class="btn" onclick="copyCheckerResults()">⧉ Salin hasil</button>
    </div>
    <div id="checkerSummary" class="grid grid-3"></div>
    <div id="checkerResults" class="mail-list"></div>
  </div>`;
}
async function runGmailChecker(){
  const emails=$("checkerEmails").value.split(/\n+/).map(x=>x.trim()).filter(Boolean);
  if(!emails.length){toast("Masukkan minimal satu email Gmail.");return}
  $("checkerResults").innerHTML='<div class="empty">Sedang memeriksa Gmail via NetNIT Deep Check…</div>';
  try{
    const r=await api("/api/checker/gmail",{method:"POST",body:JSON.stringify({emails})});
    const results=r.results||[];
    const count=st=>results.filter(x=>x.status===st).length;
    $("checkerSummary").innerHTML=
      `<div class="stat glass"><span class="label">LIVE</span><span class="big green">${count("LIVE")}</span></div>
       <div class="stat glass"><span class="label">INVALID</span><span class="big red">${count("INVALID")}</span></div>
       <div class="stat glass"><span class="label">UNKNOWN</span><span class="big orange">${count("UNKNOWN")}</span></div>`;
    $("checkerResults").innerHTML=results.map((x,i)=>{
      const cls=x.status==="LIVE"?"ok":x.status==="INVALID"?"bad":"pending";
      const label=x.status==="LIVE"?"LIVE":x.status==="INVALID"?"INVALID":"UNKNOWN";
      return `<div class="mail-row"><span>${String(i+1).padStart(2,"0")}</span><b>${esc(x.email)}</b><em class="status ${cls}" title="${esc(x.reason||"")}">${label}</em></div>`;
    }).join("")||'<div class="empty">Tidak ada hasil.</div>';
    if(r.credits!=null){
      const c=typeof r.credits==="object"?`API: ${r.credits.api??"-"} • Subscription: ${r.credits.subscription??"-"}`:`${r.credits}`;
      $("checkerResults").insertAdjacentHTML("afterbegin",`<div class="notice compact"><b>NetNIT Credits</b><br>${esc(c)}</div>`);
    }
    cache.lastChecker=results;
    toast(`Checker selesai • ${results.length} email`);
  }catch(e){
    $("checkerResults").innerHTML="";
    toast(e.message);
  }
}
async function copyCheckerResults(){
  const results=cache.lastChecker||[];
  if(!results.length){toast("Belum ada hasil checker.");return}
  const text=results.map(x=>`${x.email}\t${x.status}\t${x.reason||""}`).join("\n");
  try{await navigator.clipboard.writeText(text);toast("Hasil checker disalin")}catch{toast("Clipboard tidak tersedia")}
}

async function viewHistory(){try{cache.history=(await api("/api/history")).items||[]}catch(e){toast(e.message);return}shell("Riwayat","Semua setoran, status verifikasi, dan email yang kamu kirim.","◷","RIWAYAT");$("page").innerHTML+=`<div class="card glass"><div class="notice compact">Tap satu setoran untuk melihat <b>email satu per satu</b> yang dikirim.</div>${renderHistory(cache.history)}</div>`}
async function showSubmission(id,admin=false){try{const r=await api((admin?"/api/admin/submissions/":"/api/submissions/")+id);const sub=r.submission,items=r.items||[],emails=items.map(x=>x.email).join("\n");const rows=items.map((x,i)=>`<div class="mail-row mail-review-row"><span>${String(i+1).padStart(2,"0")}</span><div class="mail-cell"><b>${esc(x.email)}</b>${x.reason?`<small>${esc(x.reason)}</small>`:""}</div><em class="status ${x.status==="DITERIMA"?"ok":x.status==="DITOLAK"?"bad":x.status==="SEBAGIAN"?"partial":"pending"}">${esc(x.status)}</em>${admin&&x.status==="PENDING"?`<div class="item-review-actions"><button class="review-btn accept" title="Terima email ini" onclick="setSubItem(${sub.id},${x.id},'DITERIMA')">✓</button><button class="review-btn reject" title="Tolak email ini" onclick="setSubItem(${sub.id},${x.id},'DITOLAK')">×</button></div>`:`<div class="item-review-actions"><span class="review-placeholder"></span></div>`}</div>`).join("");shell(`Setoran #${sub.id}`,`${esc(sub.user_name||user?.name||"")} • ${date(sub.created_at)}`,"✉","DETAIL SETORAN");$("page").innerHTML+=`<div class="card glass detail-card"><div class="detail-summary"><div><span class="label">Status</span><strong>${esc(sub.status)}</strong></div><div><span class="label">Total</span><strong>${sub.total_items}</strong></div><div><span class="label">Diterima</span><strong class="green">${sub.accepted_items||0}</strong></div><div><span class="label">Ditolak</span><strong class="red">${sub.rejected_items||0}</strong></div></div><div class="section-title"><h2>Email yang dikirim</h2><span>${items.length} item</span></div><div class="review-legend"><span><i class="dot ok-dot"></i> ✓ Terima</span><span><i class="dot bad-dot"></i> × Tolak</span><span class="muted">Per email</span></div><div class="btn-row compact-actions"><button class="btn" onclick="copySubmission(${JSON.stringify(emails)})">⧉ Salin semua email</button>${admin&&items.some(x=>x.status==="PENDING")?`<button class="btn success" onclick="setSub(${sub.id},'DITERIMA')">✓ Terima semua pending</button><button class="btn danger" onclick="setSub(${sub.id},'DITOLAK')">× Tolak semua pending</button>`:""}</div><div class="mail-list">${rows||`<div class="empty">Tidak ada email.</div>`}</div><div class="review-help">Centang <b>✓</b> untuk email yang valid/diterima. Jika satu email rusak, tekan <b>×</b> pada email tersebut saja; email lain tetap bisa diterima dan saldo dihitung hanya dari email yang diterima.</div><button class="btn back-btn" onclick="show('${admin?"adminSub":"history"}')">← Kembali</button></div>`}catch(e){toast(e.message)}}
async function setSubItem(submissionId,itemId,status){try{await api(`/api/admin/submissions/${submissionId}/items/${itemId}/status`,{method:"POST",body:JSON.stringify({status})});toast(`Email ${status==="DITERIMA"?"diterima":"ditolak"}`);showSubmission(submissionId,true)}catch(e){toast(e.message)}}
async function copySubmission(text){if(!text){toast("Tidak ada email untuk disalin.");return}try{await navigator.clipboard.writeText(text);toast("Daftar email setoran disalin")}catch{toast("Clipboard tidak tersedia")}}
async function withdraw(){const name=$("wdName")?.value.trim(),destination=$("wdDest")?.value.trim(),amount=Number($("wdAmount")?.value),method=$("wdMethod")?.value;if(!name||!destination||!amount){toast("Lengkapi data penarikan.");return}try{const r=await api("/api/withdrawals",{method:"POST",body:JSON.stringify({name,destination,amount,method})});toast(`Penarikan ${rupiah(r.amount)} dibuat • ${r.status}`);show("profile")}catch(e){toast(e.message)}}
async function viewBalance(){try{cache.me=await api("/api/me");user=cache.me.user;cache.tx=(await api("/api/transactions")).items||[]}catch(e){toast(e.message);return}shell("Saldo & Withdraw","Kelola saldo dan ajukan penarikan.","↗","SALDO");$("page").innerHTML+=`<div class="card balance-card glass"><div class="label">Saldo tersedia</div><div class="money">${rupiah(user.balance)}</div><div class="balance-foot"><span class="reward">Penarikan diproses sesuai status transaksi</span><span class="status ok">AKTIF</span></div></div><div class="card glass"><h2>Tarik Saldo</h2><p class="muted">Minimal Rp10.000 dan kelipatan Rp1.000.</p><div class="grid"><input id="wdName" placeholder="Nama pemilik"><select id="wdMethod"><option value="DANA">DANA</option><option value="OVO">OVO</option><option value="GOPAY">GOPAY</option><option value="SHOPEEPAY">SHOPEEPAY</option><option value="LINKAJA">LINKAJA</option><option value="BANK">BANK</option></select></div><input id="wdDest" placeholder="Nomor rekening / tujuan"><input id="wdAmount" type="number" min="10000" step="1000" placeholder="Nominal penarikan"><button class="btn primary" onclick="withdraw()">Tarik Saldo</button></div><div class="card glass"><div class="section-title"><h2>Riwayat Penarikan</h2><span>Terbaru</span></div>${cache.tx.filter(x=>x.type==="PENARIKAN").slice(0,8).map(x=>`<div class="item"><div class="item-main"><b>${rupiah(Math.abs(x.amount))}</b><small>${date(x.created_at)} • ${esc(x.note||"")}</small></div><span class="status ${x.status==="SUCCESS"?"ok":x.status==="FAILED"?"bad":"pending"}">${esc(x.status)}</span></div>`).join("")||`<div class="empty">Belum ada penarikan.</div>`}</div>`}
async function viewProfile(){try{cache.me=await api("/api/me");user=cache.me.user}catch(e){toast(e.message);return}shell("Profil","Akun dan keamanan FinzyDevMail.","♙","PROFIL");$("page").innerHTML+=`<div class="card glass"><div class="row"><div><h2>${esc(user.name||"User")}</h2><div class="muted">${esc(user.email)}</div></div><span class="role-badge">${esc(user.role||"user").toUpperCase()}</span></div><hr><div class="item"><span>ID pengguna</span><b>#${user.id}</b></div><div class="item"><span>Saldo</span><b class="cyan">${rupiah(user.balance)}</b></div></div><div class="card glass"><h2>Keamanan</h2><p class="muted">Session menggunakan token JWT. Jangan bagikan token atau password.</p><button class="btn danger" onclick="logout()">Keluar dari akun</button></div>`}
async function viewAdmin(){try{cache.adminStats=await api("/api/admin/stats");cache.settings=await api("/api/admin/settings")}catch(e){toast(e.message);return}const s=cache.adminStats,price=Number(cache.settings.price_per_email||3800);shell("Admin Dashboard","Kontrol operasional FinzyDevMail dan pengaturan reward.","⌂","ADMIN");$("page").innerHTML+=`<div class="grid grid-3"><div class="stat glass"><span class="label">Anggota</span><span class="big">${s.users}</span></div><div class="stat glass"><span class="label">Setoran pending</span><span class="big orange">${s.pendingSub}</span></div><div class="stat glass"><span class="label">Tarik pending</span><span class="big red">${s.pendingWd}</span></div></div><div class="grid grid-3"><div class="stat glass"><span class="label">Rate setoran</span><span class="big cyan">${rupiah(price)}</span><small>/ email</small></div><div class="stat glass"><span class="label">Email antrean</span><span class="big">${s.pendingEmails}</span></div><button class="quick-card glass" onclick="show('adminSettings')"><span>⚙</span><b>Pengaturan</b><small>Rate & aturan setoran</small></button></div><div class="card glass"><div class="row"><div><h2>Antrean</h2><p class="muted">${s.pendingEmails} email menunggu proses</p></div><span class="status pending">LIVE</span></div><div class="btn-row"><button class="btn primary" onclick="show('adminSub')">Kelola Setoran</button><button class="btn" onclick="show('stock')">Kelola Stok</button><button class="btn" onclick="show('adminWd')">Kelola Withdraw</button><button class="btn" onclick="show('members')">Anggota</button></div></div>`}
async function viewAdminSettings(){try{cache.settings=await api("/api/admin/settings")}catch(e){toast(e.message);return}shell("Pengaturan Setoran","Atur rate/harga email dan aturan yang tampil di halaman Setoran.","⚙","ADMIN • PENGATURAN");$("page").innerHTML+=`<div class="card glass"><div class="section-title"><h2>Rate / Harga Email</h2><span>Reward saat setoran diterima</span></div><div class="setting-money"><span>Rp</span><input id="settingPrice" type="number" min="1" step="100" value="${Number(cache.settings.price_per_email||0)}"><small>per email</small></div><div class="section-title"><h2>Rules / Aturan Setoran</h2><span>Tampil ke anggota</span></div><textarea id="settingRules" class="rules-editor" rows="12">${esc(cache.settings.submission_rules||"")}</textarea><div class="notice">Gunakan satu aturan per baris agar mudah dibaca. Perubahan rate hanya memengaruhi setoran yang disetujui setelah rate baru disimpan.</div><div class="btn-row"><button class="btn primary" onclick="saveAdminSettings()">Simpan Pengaturan</button><button class="btn" onclick="show('admin')">Kembali</button></div></div>`}
async function saveAdminSettings(){const price=Number($("settingPrice")?.value),rules=$("settingRules")?.value||"";if(!Number.isFinite(price)||price<0){toast("Rate tidak valid.");return}if(rules.trim().length<10){toast("Aturan setoran terlalu pendek.");return}try{const r=await api("/api/admin/settings",{method:"PUT",body:JSON.stringify({price_per_email:price,submission_rules:rules})});cache.settings=r;toast(`Pengaturan disimpan • ${rupiah(r.price_per_email)} / email`);show("admin")}catch(e){toast(e.message)}}
async function viewAdminSub(){try{cache.adminSub=(await api("/api/admin/submissions")).items||[]}catch(e){toast(e.message);return}shell("Setoran","Validasi setoran anggota dan lihat email satu per satu.","▣","ADMIN • SETORAN");$("page").innerHTML+=`<div class="card glass"><input class="search" placeholder="Cari email/nama..." oninput="filterTable(this,'subTable')"><div class="table-wrap"><table id="subTable"><thead><tr><th>#</th><th>Anggota</th><th>Email</th><th>Item</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${cache.adminSub.map(x=>`<tr><td>${x.id}</td><td>${esc(x.user_name)}</td><td>${esc(x.user_email)}</td><td>${x.total_items}</td><td><span class="status ${x.status==="DITERIMA"?"ok":x.status==="DITOLAK"?"bad":x.status==="SEBAGIAN"?"partial":"pending"}">${x.status}</span></td><td><button class="btn" onclick="showSubmission(${x.id},true)">Detail</button> ${["PENDING","SEBAGIAN"].includes(x.status)?`<button class="btn success" onclick="setSub(${x.id},'DITERIMA')">✓ Terima pending</button> <button class="btn danger" onclick="setSub(${x.id},'DITOLAK')">× Tolak pending</button>`:""}</td></tr>`).join("")}</tbody></table></div></div>`}
async function setSub(id,status){try{const r=await api(`/api/admin/submissions/${id}/status`,{method:"POST",body:JSON.stringify({status})});toast(`Setoran #${id} → ${r.status}`);showSubmission(id,true)}catch(e){toast(e.message)}}
async function viewAdminWd(){try{cache.adminWd=(await api("/api/admin/withdrawals")).items||[]}catch(e){toast(e.message);return}shell("Withdraw","Kelola permintaan penarikan anggota.","↗","ADMIN • WITHDRAW");$("page").innerHTML+=`<div class="card glass"><div class="table-wrap"><table><thead><tr><th>#</th><th>Anggota</th><th>Metode</th><th>Tujuan</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${cache.adminWd.map(x=>`<tr><td>${x.id}</td><td>${esc(x.user_name)}<br><small>${esc(x.user_email)}</small></td><td>${esc(x.method)}</td><td>${esc(x.destination)}</td><td>${rupiah(x.amount)}</td><td><span class="status ${x.status==="DISETUJUI"?"ok":x.status==="DITOLAK"?"bad":x.status==="SEBAGIAN"?"partial":"pending"}">${x.status}</span></td><td>${x.status==="PENDING"?`<button class="btn success" onclick="setWd(${x.id},'DISETUJUI')">Setujui</button> <button class="btn danger" onclick="setWd(${x.id},'DITOLAK')">Tolak</button>`:"—"}</td></tr>`).join("")}</tbody></table></div></div>`}
async function setWd(id,status){try{await api(`/api/admin/withdrawals/${id}/status`,{method:"POST",body:JSON.stringify({status})});toast(`Withdraw #${id} → ${status}`);show("adminWd")}catch(e){toast(e.message)}}
async function viewStock(){try{const r=await api("/api/admin/stock");cache.stock=r.items||[]}catch(e){toast(e.message);return}const available=cache.stock.filter(x=>x.status==="AVAILABLE").length;const claimed=cache.stock.filter(x=>x.status==="CLAIMED").length;shell("Stok Generate","Admin memasukkan email yang boleh dipakai sebagai stok. Hanya alamat email yang disimpan; password/OTP tidak diterima.","✦","ADMIN • STOK");$("page").innerHTML+=`<div class="grid grid-3"><div class="stat glass"><span class="label">Tersedia</span><span class="big cyan">${available}</span></div><div class="stat glass"><span class="label">Sudah diambil</span><span class="big">${claimed}</span></div><div class="stat glass"><span class="label">Total stok</span><span class="big">${cache.stock.length}</span></div></div><div class="card glass"><div class="section-title"><h2>Isi stok</h2><span>1 email / baris • max 1.000</span></div><textarea id="stockEmails" placeholder="email1@gmail.com\nemail2@gmail.com"></textarea><div class="btn-row"><button class="btn primary" onclick="addStock()">＋ Tambah ke Stok</button><button class="btn" onclick="$(\'stockEmails\').value=\'\'">Bersihkan</button></div></div><div class="card glass"><div class="section-title"><h2>Daftar stok</h2><span>${available} tersedia</span></div><div class="stock-list">${cache.stock.slice(0,200).map(x=>`<div class="mail-row"><span>#${x.id}</span><b>${esc(x.email)}</b><em class="status ${x.status==="AVAILABLE"?"ok":"pending"}">${x.status}</em>${x.status==="AVAILABLE"?`<button class="icon-delete" onclick="deleteStock(${x.id})">×</button>`:""}</div>`).join("")||`<div class="empty">Belum ada stok.</div>`}</div></div>`}
async function addStock(){const emails=$("stockEmails").value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!emails.length){toast("Masukkan email stok.");return}try{const r=await api("/api/admin/stock",{method:"POST",body:JSON.stringify({emails})});toast(`${r.added} email ditambahkan • ${r.duplicates} duplikat`);show("stock")}catch(e){toast(e.message)}}
async function deleteStock(id){try{await api(`/api/admin/stock/${id}`,{method:"DELETE"});toast("Stok dihapus");show("stock")}catch(e){toast(e.message)}}
async function viewMembers(){try{cache.members=(await api("/api/admin/users")).items||[]}catch(e){toast(e.message);return}shell("Anggota","Daftar akun, role, saldo, dan aktivitas anggota.","♙","ADMIN • ANGGOTA");$("page").innerHTML+=`<div class="card glass"><input class="search" placeholder="Cari anggota..." oninput="filterTable(this,'memberTable')"><div class="table-wrap"><table id="memberTable"><thead><tr><th>ID</th><th>Nama</th><th>Email</th><th>Role</th><th>Saldo</th><th>Aksi</th></tr></thead><tbody>${cache.members.map(x=>`<tr><td>#${x.id}</td><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.role)}</td><td>${rupiah(x.balance)}</td><td><button class="btn" onclick="adjustBalance(${x.id})">Atur saldo</button></td></tr>`).join("")}</tbody></table></div></div>`}
function adjustBalance(id){const amount=prompt("Masukkan penyesuaian saldo. Contoh: 10000 atau -5000");if(amount===null)return;const note=prompt("Catatan","Penyesuaian admin");api(`/api/admin/users/${id}/balance`,{method:"POST",body:JSON.stringify({amount:Number(amount),note:note||"Penyesuaian admin"})}).then(()=>{toast("Saldo diperbarui");show("members")}).catch(e=>toast(e.message))}
function filterTable(input,id){const q=input.value.toLowerCase();document.querySelectorAll(`#${id} tbody tr`).forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(q)?"":"none")}
boot();
